### ISSUE TITLE
Serialize fails on generating project triggers

### ISSUE THREAD

**Issue by ryanrousseau** [OctopusSolutionsEngineering/OctopusTerraformExport#24]
### Octopus version

2024.2.6366

### Octoterra version

latest

### What happened

Serialization of project started failing after adding scheduled triggers (deploy new release and deploy latest release)

### Octoterra log output

```Exporting Terraform module 
2024-04-29T16:26:33.809Z	debug	Getting collection Projects 
2024-04-29T16:26:34.221Z	info	Exporting project(s) Projects-4137 in space Spaces-178 
2024-04-29T16:26:34.221Z	debug	Getting Projects Projects-4137 
2024-04-29T16:26:34.374Z	info	Project: Projects-4137 
2024-04-29T16:26:34.374Z	debug	Getting ProjectGroups ProjectGroups-3528 
2024-04-29T16:26:34.414Z	debug	Getting Lifecycles Lifecycles-284 
2024-04-29T16:26:34.443Z	debug	Getting Git-Credentials GitCredentials-922 
2024-04-29T16:26:34.483Z	debug	Getting collection Projects/Projects-4137/channels 
2024-04-29T16:26:34.527Z	debug	Getting Channels Projects-4137 
2024-04-29T16:26:34.563Z	info	Channel: Channels-4836 
2024-04-29T16:26:34.563Z	debug	Getting Projects/Projects-4137/Variables 
2024-04-29T16:26:34.945Z	debug	Cache hit on Projects Projects-4137 
2024-04-29T16:26:34.945Z	info	VariableSet: variableset-Projects-4137 
2024-04-29T16:26:34.945Z	debug	Getting collection Projects/Projects-4137/Triggers 
2024-04-29T16:26:35.009Z	info	Project Trigger: ProjectTriggers-1348 
2024-04-29T16:26:35.009Z	info	Project Trigger: ProjectTriggers-1347 
2024-04-29T16:26:35.009Z	info	Project Trigger: ProjectTriggers-1349 
2024-04-29T16:26:35.010Z	info	Project Trigger: ProjectTriggers-1344 
2024-04-29T16:26:35.010Z	info	Project Trigger: ProjectTriggers-1345 
2024-04-29T16:26:35.010Z	info	Project Trigger: ProjectTriggers-1346 
2024-04-29T16:26:35.010Z	debug	Getting collection Projects/Projects-4137/runbooks 
2024-04-29T16:26:35.043Z	info	Generating HCL (this can take a little while) 
2024-04-29T16:26:35.044Z	error	Failed to resolve lookup  of type Channels 
2024-04-29T16:26:35.044Z	error	Failed to resolve lookup Environments-277 of type Environments 
2024-04-29T16:26:35.044Z	error	Failed to resolve lookup  of type Channels 
2024-04-29T16:26:35.044Z	error	Failed to resolve lookup Environments-278 of type Environments 
2024-04-29T16:26:35.044Z	error	Failed to resolve Environments-277 of type Environments 
2024-04-29T16:26:35.044Z	error	Failed to resolve dependency Spaces-178 of type Spaces 
panic: runtime error: index out of range [0] with length 0 
goroutine 70 [running]: 
github.com/OctopusSolutionsEngineering/OctopusTerraformExport/cmd/internal/converters.ProjectTriggerConverter.buildDeployLatestReleaseAction({{_, _}, _, _, _}, {{0xc000198f60, 0x14}, {0xc000198f78, 0x14}, 0xc00032ec60, ...}, ...) 
	/app/cmd/internal/converters/project_trigger_converter.go:589 +0x165 
github.com/OctopusSolutionsEngineering/OctopusTerraformExport/cmd/internal/converters.ProjectTriggerConverter.buildScheduledTrigger.func1() 
	/app/cmd/internal/converters/project_trigger_converter.go:348 +0x5a8 
github.com/OctopusSolutionsEngineering/OctopusTerraformExport/cmd/internal/entry.ProcessResources.func1() 
	/app/cmd/internal/entry/entry.go:1739 +0x6c 
created by github.com/OctopusSolutionsEngineering/OctopusTerraformExport/cmd/internal/entry.ProcessResources in goroutine 1 
	/app/cmd/internal/entry/entry.go:1737 +0x245 
Octoterra failed. Please check the logs for more information. ```

### Reproduction steps

Runbook found at https://demo.octopus.app/app#/Spaces-178/projects/octopub-yaml-serializer/operations/runbooks/Runbooks-7736/runslist

### More Information

_No response_

**Comment by ryanrousseau** [comment]
This appears to only impact the Deploy Latest release option, projects with triggers that create releases are serializing successfully

**Comment by mcasperson** [comment]
The error shown in the logs was due to an empty array being indexed. This has been addressed.

The root cause still needs to be fixed though, which is that the environments can not be resolved i.e. these errors:

* `Failed to resolve lookup Environments-277 of type Environments`
* `Failed to resolve lookup Environments-278 of type Environments`
